// svelte/src/features/cats/components/Cat.svelte
<script lang="ts">
  import { HOME_ROUTE } from '@constants/route.constants';
  import { useCatByIdQuery } from '@hooks/cat.hooks';
  import { navigateToRouteAndSetCurrentRouteStore } from '@utils/router.utils';

  export let id: string;

  const catById = useCatByIdQuery({ data: id });

</script>

<div class="prose mt-4 dark:prose-invert">
  <button type="button" on:click={() => navigateToRouteAndSetCurrentRouteStore(HOME_ROUTE)} >
    Back
  </button>
  <h1>{$catById.data?.cat_by_id?.name || ''}</h1>
</div>

// react/src/features/cats/components/cat.component.tsx
import { Link, useParams } from 'react-router-dom';

import useFindCatById from '../hooks/find-cat-by-id.hook';

function Cat() {
  const { catId } = useParams();
  const { data } = useFindCatById({ id: catId as string });

  return (
    <div className="prose mt-4 dark:prose-invert">
      <Link to="/cats">
        <button type="button" >
          Back
        </button>
      </Link>
      <h1>{data?.name}</h1>
    </div>
  );
}

export default Cat;
