// svelte/src/App.svelte
<script lang="ts">
  import './app.css';
  import { QueryClientProvider } from '@tanstack/svelte-query';

  import { Notification } from '@features/notification/components';
  import QueryClientSingleton from '@providers/svelte-query-client.provider';

  import AppRoutes from './routes/AppRoutes.svelte';
</script>

<QueryClientProvider client={QueryClientSingleton.getInstance()}>
  <AppRoutes/>
  <Notification/>
</QueryClientProvider>

// react/src/App.tsx
import { Banner } from '@features/banner';
import { ErrorBoundary } from '@features/error-boundary';
import { Notification } from '@features/notification';
import QueryClientSingleton from '@providers/react-query-client.provider';
import AppRoutes from '@routes/app.routes';
import { QueryClientProvider } from '@tanstack/react-query';

export default function App() {
  return (
    <QueryClientProvider client={QueryClientSingleton.getInstance()}>
      <ErrorBoundary>
        <AppRoutes />
        <Banner />
        <Notification />
      </ErrorBoundary>
    </QueryClientProvider>
  );
}
