// svelte/src/components/loading/LoadingLayoutOnFetching.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';

  import { fetchesBeingPerformedStore } from '@stores/fetches-being-performed.store';

  import LoadingLayout from './LoadingLayout.svelte';

  let fetchesBeingPerformed: number;

  const unsubscribe = fetchesBeingPerformedStore.subscribe((n) => { fetchesBeingPerformed = n; });

  onDestroy(unsubscribe);
</script>

{#if fetchesBeingPerformed > 0}
  <LoadingLayout isSuspense={false} />
{/if}

// react/src/components/loading/loading-layout-on-fetching.component.tsx
import { fetchesBeingPerformedAtom } from '@atoms/fetches-being-performed.atom';
import { useAtom } from 'jotai';

import LoadingLayout from './loading-layout.component';

export default function LoadingLayoutOnFetching() {
  const [fetchesBeingPerformed] = useAtom(fetchesBeingPerformedAtom);

  return (
    (fetchesBeingPerformed > 0) ? <LoadingLayout isSuspense={false} /> : <div />
  );
}
