// react/src/features/home/components/layout.component.tsx
import { LoadingLayout, LoadingLayoutOnFetching } from '@components/loading';
import { lazy, Suspense } from 'react';
import { Outlet } from 'react-router-dom';

const ForbiddenAccessModal = lazy(() => import('@components/modals/forbidden-access-modal.component'));

export default function Layout() {
  return (
    // A surrounding 'div' is necessary because of the Loading component
    // css 'absolute' position; without it, would override the navbar menu. 
    <div className="flex flex-col">
      <Suspense fallback={<LoadingLayout />} >
        <ForbiddenAccessModal />
        <LoadingLayoutOnFetching />
        <div className="px-4 sm:px-12 md:px-24 lg:px-36 xl:px-48 2xl:px-60">
          <Outlet />
        </div>
      </Suspense>
    </div>
  );
}

// svelte/src/features/home/components/Layout.svelte
<script lang="ts">
  import { LoadingLayoutOnFetching } from '@components/loading';
  import ForbiddenAccessModal from '@components/modals/ForbiddenAccessModal.svelte';
  import { showForbiddenAccessModalStore } from '@stores/show-forbidden-access-modal.store';

  import LayoutRoutes from '../routes/LayoutRoutes.svelte';
</script>

<div class="flex flex-col">
  {#if $showForbiddenAccessModalStore}
    <ForbiddenAccessModal/>
  {/if}
  <LoadingLayoutOnFetching/>
  <div class="px-4 sm:px-12 md:px-24 lg:px-36 xl:px-48 2xl:px-60">
    <LayoutRoutes />
  </div>
</div>
